#!/usr/bin/env bash
#Usage: application-cmd [nodes] [inputfile]
#Use the intel mpi exists in CentOS-HPC 7.4 image
source /opt/intel/impi/5.1.3.223/bin64/mpivars.sh
export I_MPI_FABRICS=tcp
export I_MPI_DAPL_PROVIDER=ofa-v2-ib0
export I_MPI_DYNAMIC_CONNECTION=0
mpirun -n $1  -hosts $AZ_BATCH_HOST_LIST $AZ_BATCH_APP_PACKAGE_aout_1/bing $2 $3 $4 $5| sort